version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lib
      POSTGRES_USER: annie
      POSTGRES_PASSWORD: inkcherry
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    working_dir: /app

  app:
    image: node:latest
    command: bash -c "npx prisma migrate dev --name init && npx prisma db seed && tail -f /dev/null"
    ports:
      - "3000:3000"

    volumes:
      - ./next:/app
    working_dir: /app
