services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lib
      POSTGRES_USER: annie
      POSTGRES_PASSWORD: inkcherry
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    working_dir: /app

  app:
    image: node:latest
    # command: bash -c "npx prisma migrate dev --name init && npx prisma generate && npx prisma db seed && tail -f /dev/null"
    # command: bash -c "npx prisma migrate dev --name init && npx prisma generate && npx prisma db seed"
    # command: bash -c "npx prisma migrate dev --name init && npx prisma generate && npx prisma db seed && npm install && npm run build && npm run start"
    command: npm run start
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./next:/app
    working_dir: /app
