services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lib
      POSTGRES_USER: annie
      POSTGRES_PASSWORD: inkcherry
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    working_dir: /app

  app:
    image: node:latest
    command: bash -c "tail -f /dev/null"
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./next:/app
    working_dir: /app
